const { Schema , model } = require('mongoose');

const recipeSchema = new Schema({
    id:{
        type:String,
        unique:true,
        required:true
    },
    recipe_name:{
        type:String,
        required:true
    },
    images:[{
        type:String,
        required:true
    }],
    author_id:{
        type:String,
        required:true
    },
    author:{
        type:String,
        required:true,
        ref:'users'
    },
    posted_on:{
        type:String,
        required:true
    },
    number_of_favorites:{
        type:Number,
        required:true
    },
    ratings:{
        total_rating:{
            type:Number,
            required:true
        },
        number_of_ratings:{
            type:Number,
            required:true
        },
        average_rating:{
            type:Number,
            required:true
        }
    },
    description:{
        type:String,
        required:true
    },
    tags:[{
        type:String,
        required:true
    }],
    preparation_time:{
        type:String,
        required:true
    },
    cooking_time:{
        type:String,
        required:true
    },
    additional_timings:[{
        key:{
            type:String,
            required:true
        },
        value:{
            type:String,
            required:true
        }
    }],
    difficulty:{
        type:String,
        required:true
    },
    ingredients:[{
        type:String,
        required:true
    }],
    stuffings:[{
        type:String,
        required:true
    }],
    steps:[{
        step:{
            type:String,
            required:true
        },
        ref_img:{
            type:String,
            required:true
        }
    }],
    comments:[{
        user_pfp:{
            type:String,
            required:true
        },
        user_name:{
            type:String,
            required:true
        },
        rating:{
            type:Number,
            required:true
        },
        commented_on:{
            type:String,
            required:true
        },
        likes:{
            type:Number,
            required:true
        },
        comment:{
            type:String,
            required:true
        },
        replies:[{
            user_pfp:{
                type:String,
                required:true
            },
            user_name:{
                type:String,
                required:true
            },
            replied_on:{
                type:String,
                required:true
            },
            reply:{
                type:String,
                required:true
            },
            replying_to:{
                type:String,
                required:true
            }
        }]
    }]
});

const Recipe = model('Recipes',recipeSchema);

module.exports = Recipe;